module.exports={
    selectAllDestination:"SELECT * FROM destination",
    updateUserLand:"UPDATE user_land SET land=? WHERE id=?",
    insertDestination: "INSERT INTO destination VALUES (?,?,?,?,?,?,?,?)",
    deleteDestination: "DELETE FROM destination WHERE id >=1 AND id <=100",
    insertLand: "INSERT INTO taxi_land VALUES (?,?)",
    updateLand: "UPDATE taxi_land SET land_id=? WHERE taxi_id = ?",
    deleteLand: "DELETE FROM taxi_land",
    insertDriveInfo: "INSERT INTO drive_info_ VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
    deleteDriveInfo: "DELETE FROM drive_info_",
    updateDriveInfoCurLoc: "UPDATE drive_info_ SET cur_loc_x=?,cur_loc_y=? WHERE taxi_id=?",
    updateDriveInfoNoSearch: "UPDATE drive_info_ SET no_search=? WHERE drive_id=?",
    updateDriveInfo: "UPDATE drive_info_ SET guest_id=?, route=?, total_dist=?,cost=?,dest_x=?,dest_y=? WHERE drive_id = ?",
    deleteDriveInfoCustomer: "DELETE FROM drive_info_ WHERE host_id in (?) or guest_id in (?)",
    selectDestination: "SELECT * FROM destination",
    selectIdDestination: "SELECT * FROM destination WHERE id = ?",
    insertUserLand: "INSERT INTO user_land VALUES(?,?)",
    deleteUserLand: "DELETE FROM user_land",
    updateUserLand: "UPDATE user_land SET land_id= ? WHERE id= ?",
    deleteIdDestination : "DELETE FROM destination WHERE id = ?",
    deleteIdUserLand : "DELETE FROM user_land WHERE id = ?"
}